# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Quality Control

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11" ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements-dev.txt
        python3 -m pip install wheel
    - name: Run integrity checks
      run: |
        pycodestyle --format=pylint rkvst_simplehash unittests
        python3 -m pylint rkvst_simplehash unittests
        black rkvst_simplehash unittests
        modified=$(git status -s | wc -l)
        if [ $modified -gt 0 ]
        then
            echo "there are $modified files that must be reformatted"
            exit 1
        fi
        ./scripts/unittests.sh
        rm -f coverage.xml
        rm -rf htmlcov
        coverage run --branch --source rkvst_simplehash -m unittest -v

